GET http://localhost:5000/api/members

###

GET http://localhost:5000/api/members/1

###
POST http://localhost:5000/api/members
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Blaine"
}

###
POST http://localhost:5000/api/members
Content-Type: application/json

{
    "firstName": "David",
    "lastName": ""
}

###
PUT http://localhost:5000/api/members/1
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Squared"
}

###

DELETE http://localhost:5000/api/members/2

